version: "3"

services:
  app:
    container_name: Jagaad-frontend-task
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  cypress:
    image: "cypress/included:3.2.0"
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:8080
    working_dir: /e2e
    volumes:
      - ./:/e2e
